### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by kjblack** [hassio-addons/addon-overseerr#14]
Randomly crashed and failing to start:

‘
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service overseerr: starting
s6-rc: info: service overseerr successfully started
s6-rc: info: service legacy-services: starting
[22:05:01] INFO: Starting Overseerr...
s6-rc: info: service legacy-services successfully started
yarn run v1.22.19
$ NODE_ENV=production node dist/index.js
2024-06-09T21:05:03.353Z [info]: Commit Tag: v1.33.2 
2024-06-09T21:05:03.749Z [info]: Starting Overseerr version 1.33.2 
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

2024-06-09T21:05:04.900Z [error]: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Settings.load (/opt/dist/lib/settings.js:305:61)
    at /opt/dist/index.js:80:52 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[22:05:04] INFO: Service Overseerr exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service overseerr: stopping
s6-rc: info: service overseerr successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Overseerr
 Request management and media discovery tool for the Plex ecosystem
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (amd64 / qemux86-64)
 Home Assistant Core: 2024.6.1
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service overseerr: starting
s6-rc: info: service overseerr successfully started
s6-rc: info: service legacy-services: starting
[22:05:09] INFO: Starting Overseerr...
s6-rc: info: service legacy-services successfully started
yarn run v1.22.19
$ NODE_ENV=production node dist/index.js
2024-06-09T21:05:11.223Z [info]: Commit Tag: v1.33.2 
2024-06-09T21:05:11.565Z [info]: Starting Overseerr version 1.33.2 
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

2024-06-09T21:05:12.667Z [error]: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Settings.load (/opt/dist/lib/settings.js:305:61)
    at /opt/dist/index.js:80:52 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[22:05:12] INFO: Service Overseerr exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service overseerr: stopping
s6-rc: info: service overseerr successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

`

**Comment by Jayraydee** [comment]
I am also having issues with overseer failing to start on my HA install, I get a "internal server error" whenever I try to open the overseer page. 

Here's the log results I get after the overseer crashes:

    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/api/v1/settings/public',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '5055',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/v1/settings/public'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/v1/settings/public HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.3.4\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:5055\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v1/settings/public',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:5055/api/v1/settings/public',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ::1:5055
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5055
  }
}

**Comment by cptjhmiller** [comment]
Same for me.

**Comment by jcnicholls123** [comment]
Same for me HAOS 12.4

**Comment by mwilky** [comment]
Yep started getting internal server error now

**Comment by mikenhu** [comment]
Same for me here.

**Comment by juhenriquez** [comment]
Same here

**Comment by schafran** [comment]
same.

**Comment by samsamsamiam** [comment]
Me too

**Comment by schafran** [comment]
I switched to the Overseerr Add-On in alexbelgium's repository for the time being: [https://github.com/alexbelgium/hassio-addons](https://github.com/alexbelgium/hassio-addons)

**Comment by deanrparry** [comment]
This is why I don't run home assistant operating system rarely see issues like this in docker containers. Shame as I really want the easy life 🤣

1 month and no fix

**Comment by samsamsamiam** [comment]
> I switched to the Overseerr Add-On in alexbelgium's repository for the time being: https://github.com/alexbelgium/hassio-addons

This one is working, thank you! @schafran

**Comment by miguelangellv** [comment]
> I switched to the Overseerr Add-On in alexbelgium's repository for the time being: https://github.com/alexbelgium/hassio-addons

I switched too and coping the db and settings file from one to other I did not need configure anything.

**Comment by miguelangellv** [comment]
The problem is not solved, don't close it.
